<a href="https://colab.research.google.com/github/lblogan14/master_tensorflow_keras/blob/master/ch1_tensorflow101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Models of the TensorFlow:
* **data model**, consisting of tensors
* **programming model**, consisting of data flow graphs or computation graphs
* **execution mode**l, consisting of firing the nodes in a sequence based on the dependence conditions, starting from the initial nodes that depend on inputs

* **lower-level library**, also known as TensorFlow core,
provides very fine-grained lower level functionality, thereby offering complete
control on how to use and implement the library in the models.
* **higher-level library**, provides high-level functionalities and are
comparatively easier to learn and implement in the models. Some of the libraries
include TF Estimators, TFLearn, TFSlim, Sonnet, and Keras.

#TensorFlow core
## Code warm up - Hello TensorFlow

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tfs = tf.InteractiveSession()

TensorFlow offers two kinds of sessions: **Session()** and **InteractiveSession()**.

The session created with **InteractiveSession()** becomes the default session. Thus, we do not need to specify the session context to
execute the session-related command later. 

For example, say that we have a session object, **tfs**, and a constant object, **hello**. If tfs is an **InteractiveSession()** object, then we can evaluate hello with the code **hello.eval()**. If **tfs** is a **Session()** object, then we have to use either **tfs.hello.eval()** or a **with** block. The most common practice is to use the **with** block.

In [3]:
hello = tf.constant('Hello TensorFlow !!')
print(tfs.run(hello))

b'Hello TensorFlow !!'


##Tensors,
is an n-dimensional collection of data, identified by rank, shape, and type.
* *rank*, number of dimensions of a tensor
* *shape*, a list denoting a size in each dimension
* *type*, data type

##Constants
    tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

In [0]:
c1=tf.constant(5,name='x')
c2=tf.constant(6.0,name='y')
c3=tf.constant(7.0,tf.float32,name='z')

In [5]:
print('c1 (x): ',c1)
print('c2 (y): ',c2)
print('c3 (z): ',c3)

c1 (x):  Tensor("x:0", shape=(), dtype=int32)
c2 (y):  Tensor("y:0", shape=(), dtype=float32)
c3 (z):  Tensor("z:0", shape=(), dtype=float32)


In order to print the values of these constants, we have to execute them in a TensorFlow
session with the **tfs.run()** command:

In [6]:
print('run([c1, c2, c3]) : ', tfs.run([c1, c2, c3]))

run([c1, c2, c3]) :  [5, 6.0, 7.0]


##Operations

In [0]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)

In [8]:
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add:0", shape=(), dtype=float32)
op2 :  Tensor("Mul:0", shape=(), dtype=float32)


To print the value of these operations, we have to run them in our TensorFlow session:

In [9]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  13.0
run(op2) :  42.0


built-in operations,
* Arithmetic,
    
    `tf.add, tf.subtract, tf.multiply, tf.scalar_mul, tf.div, tf.divide, tf.truediv, tf.floordiv, tf.realdiv, tf.truncatediv, tf.floor_div, tf.truncatemod, tf.floormod, tf.mod, tf.cross`
* Basic math,

    `tf.add_n, tf.abs, tf.negative, tf.sign, tf.reciprocal,
tf.square, tf.round, tf.sqrt, tf.rsqrt, tf.pow, tf.exp, tf.expm1,
tf.log, tf.log1p, tf.ceil, tf.floor, tf.maximum, tf.minimum,
tf.cos, tf.sin, tf.lbeta, tf.tan, tf.acos, tf.asin, tf.atan,
tf.lgamma, tf.digamma, tf.erf,
tf.erfc, tf.igamma, tf.squared_difference, tf.igammac, tf.zeta,
tf.polygamma, tf.betainc, tf.rint`

* Matrix math,

    `tf.diag, tf.diag_part, tf.trace,
tf.transpose, tf.eye, tf.matrix_diag, tf.matrix_diag_part,
tf.matrix_band_part, tf.matrix_set_diag, tf.matrix_transpose,
tf.matmul, tf.norm, tf.matrix_determinant, tf.matrix_inverse,
tf.cholesky, tf.cholesky_solve, tf.matrix_solve,
tf.matrix_triangular_solve, tf.matrix_solve_ls, tf.qr,
tf.self_adjoint_eig, tf.self_adjoint_eigvals, tf.svd`

* Tensor math,

    `tf.tensordot`
    
* Complex number,
    
    `tf.complex, tf.conj, tf.imag, tf.real`
    
* String,

    `tf.string_to_hash_bucket_fast, tf.string_to_hash_bucket_strong,
tf.as_string, tf.encode_base64, tf.decode_base64,
tf.reduce_join, tf.string_join, tf.string_split, tf.substr,
tf.string_to_hash_bucket`

##Placeholders
allow to create tensors whose values can be provided at runtime.

`tf.placeholder(dtype, shape=None, name=None)`

In [10]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [0]:
op4 = p1 * p2

`p1 * p2` is shorthand for `tf.multiply(p1,p2)`:

In [13]:
print('run(op4, {p1:2.0, p2:3.0}) : ', tfs.run(op4, {p1:2.0, p2:3.0}))

run(op4, {p1:2.0, p2:3.0}) :  6.0


or you can specify the dictionary using the `feed_dict` parameter,

In [14]:
print('run(op4, feed_dict={p1:3.0, p2:4.0})) : ',
     tfs.run(op4, feed_dict={p1:3.0, p2:4.0}))

run(op4, feed_dict={p1:3.0, p2:4.0})) :  12.0


In [15]:
print('run(op4,feed_dict = {p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}) : ',
tfs.run(op4,feed_dict = {p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}))
# element-wise

run(op4,feed_dict = {p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}) :  [ 6. 12. 20.]


##Creating tensors from Python objects
`tf.convert_to_tensor(value, dtype=None, name=None, preferred_dtype = None)`

`tf.convert_to_tensor()` creates tensors from Python objects

0-D tensor,

In [16]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)
print('tf_t : ', tf_t)
print('run(tf_t) : ', tfs.run(tf_t))

tf_t :  Tensor("Const_1:0", shape=(), dtype=float64)
run(tf_t) :  5.0


1-D tensor,

In [19]:
a1dim = np.array([1,2,3,4,5.99])
print('a1dim Shape : ', a1dim.shape)

a1dim Shape :  (5,)


In [0]:
tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

In [21]:
print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[2] : ', tf_t[2])
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[2] :  Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


2-D tensor,

In [22]:
a2dim = np.array([(1,2,3,4,5.99),
                  (2,3,4,5,6.99),
                  (3,4,5,6,7.99)
])
print("a2dim Shape : ",a2dim.shape)

a2dim Shape :  (3, 5)


In [0]:
tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

In [24]:
print('tf_t : ',tf_t)
print('tf_t[0][0] : ',tf_t[0][0])
print('tf_t[1][2] : ',tf_t[1][2])
print('run(tf_t) : \n',tfs.run(tf_t))

tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


3-D tensor,

In [25]:
a3dim = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]
])
print("a3dim Shape : ",a3dim.shape)

a3dim Shape :  (2, 2, 2)


In [26]:
tf_t=tf.convert_to_tensor(a3dim,dtype=tf.float64)
print('tf_t : ',tf_t)
print('tf_t[0][0][0] : ',tf_t[0][0][0])
print('tf_t[1][1][1] : ',tf_t[1][1][1])
print('run(tf_t) : \n',tfs.run(tf_t))

tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


##Variables
`tf.Variable`

`tf.placeholder` | `tf.Variable`
--- | ---
`tf.placeholder` defines input data that does not change over time | `tf.Variable` defines variable values that are modified over time
`tf.placeholder` does not need an initial value at the time of definition | `tf.Variable` needs an initial value at the time of definition

For a simple linear model
$$y=W \times x + b$$
define model parameters as variables with initial values of `[0.3]` and `[-0.3]`

In [0]:
w = tf.Variable([0.3], tf.float32)
b = tf.Variable([-0.3], tf.float32)

In [0]:
x = tf.placeholder(tf.float32)
y = w * x + b

In [29]:
print("w:",w)
print("x:",x)
print("b:",b)
print("y:",y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_1:0", dtype=float32)


Before you can use the variables in a TensorFlow session, they have to be initialized.

In [0]:
tfs.run(w.initializer)

Or you can try,

In [0]:
tfs.run(tf.global_variables_initializer())

This is equivalent to `tf.global_varaibles_initializer().run()`

You can also use the `tf.variables_initializer()` function to
initialize only a set of variables.

Now run the model,

In [31]:
print('run(y, {x:[1,2,3,4]}) : ', tfs.run(y, {x:[1,2,3,4]}))

run(y, {x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


#Tensors generated from library functions

In [32]:
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


TensorFlow provides different types of functions to populate the tensors at the time of their
definition:
* Populating all elements with the same values
* Populating elements with sequences
* Populating elements with a random probability distribution, such as the normal
distribution or the uniform distribution

##Populating tensor elements with the same values
* `zeros(shape, dtype=tf.float32, name=None)`, creates a tensor of the provided shape, with all elements set to
zero
* `zeros_like(tensor, dtype=None, name=None, optimize=True)`, creates a tensor of the same shape as the argument, with all
elements set
* `ones(shape, dtype=tf.float32, name=None)`, creates a tensor of the provided shape, with all elements set to
one
* `ones_like(tensor, dtype=None, name=None, optimize=True)`,  creates a tensor of the same shape as the argument, with all
elements set to one
* `fill(dims, value, name=None)`, creates a tensor of the shape as the `dims` argument, with all elements set to `value`; for example, `a = tf.fill([100],0)`

##Populating tensor elements with sequences
* `lin_space(start, stop, num, name=None)`, generates a 1-D tensor from a sequence of num numbers within the
range `[start, stop]`. The tensor has the same data type as the `start` argument.
* `range(limit, delta=1, dtype=None, name='range')`
* `range(start, limit, delta=1, dtype=None, name='range')`, generates a 1-D tensor from a sequence of numbers within the range `[start, limit]`, with the increments of `delta`. If the `dtype` argument is not specified, then the tensor has the same data type as the `start` argument. This function comes in two versions. In the second version, if the `start` argument is omitted, then `start` becomes number 0.

##Populating tensor elements with a random distribution
The distributions generated are affected by the graph-level or the operation-level seed. 
* The graph-level seed is set using `tf.set_random_seed`
* The operation-level seed is given as the argument `seed` in all of the random distribution functions. If no seed is specified,
then a random seed is used.

* `random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)`, generates a tensor of the specified shape, filled with values from a normal distribution: `normal(mean, stddev)`.
* `truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)`, generates a tensor of the specified shape, filled with values from a truncated normal distribution: `normal(mean, stddev)`. Truncated means that the values returned are always at a distance less than two standard deviations from the mean.
* `random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)`, generates a tensor of the specified shape, filled with values from a uniform distribution: `uniform([minval, maxval))`.
* `random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)`, generates tensors of the specified shape, filled with values from gamma distributions: `gamma(alpha,beta)`.

#Getting Variables with `tf.get_variable()`
If you define a variable with a name that has been defined before, then TensorFlow throws
an exception. Hence, it is convenient to use the `tf.get_variable()` function instead of
`tf.Variable()`.

`tf.get_variable()` returns the existing variable with the
same name if it exists, and creates the variable with the specified shape and initializer if it
does not exist.

In [0]:
w = tf.get_variable(name='w',shape=[1],dtype=tf.float32,initializer=[.3])
b = tf.get_variable(name='b',shape=[1],dtype=tf.float32,initializer=[-.3])

The initializer can be a tensor or list of values as shown in above examples or one of the
inbuilt initializers:
* `tf.constant_initializer`
*  `tf.random_normal_initializer`
* `tf.truncated_normal_initializer`
* `tf.random_uniform_initializer`
* `tf.uniform_unit_scaling_initializer`
* `tf.zeros_initializer`
* `tf.ones_initializer`
* `tf.orthogonal_initializer`

In distributed TensorFlow where we can run the code across machines, the
`tf.get_variable()` gives us global variables. Use `tf.get_local_variable()` instead

**Sharing or Reusing Variables**: Getting already-defined variables promotes reuse.
However, an exception will be thrown if the reuse flags are not set by using
`tf.variable_scope.reuse_variable()` or `tf.variable.scope(reuse=True)`.

#Data flow graph or computation graph
Each node represents an operation (`tf.Operation`) and each
edge represents a tensor (`tf.Tensor`) that gets transferred between the nodes.

The TensorFlow comes with a default graph. Unless another graph is explicitly specified, a
new node gets implicitly added to the default graph. Access to the default graph:

`graph = tf.get_default_graph()`

As we create the variables, constants, and placeholders, they get added to the graph. Then
we create a `session` object to *execute* the operation objects and *evaluate* the tensor objects.

In [0]:
# Close the interactive session
tfs.close()

In [0]:
# Assume Linear model y = w * x + b
# model parameters
w = tf.Variable([0.3], tf.float32)
b = tf.Variable([-0.3], tf.float32)
# input/output
x = tf.placeholder(tf.float32)
y = w * x + b
ouput = 0

Creating and using a session in the `with` block ensures that the session is automatically
closed when the block is finished. Otherwise, the session has to be explicitly closed with
the `tfs.close()` command, where `tfs` is the session name.

In [36]:
with tf.Session() as tfs:
  # initiailze and print the variable y
  tf.global_variables_initializer().run()
  output = tfs.run(y, {x:[1,2,3,4]})
print('output: ', output)

output:  [0.         0.3        0.6        0.90000004]


#Order of execution and lazy loading
lazy loading: the mode objects are not created and initialized until they are needed.

Use `tf.Graph.control_dependencies()` to control the order in which the nodes are executed in a graph. For example, if the graph has nodes *a, b, c,* and *d* and you want to execute *c* and *d* before *a* and *b*,

    with graph_variable.control_dependencies([c,d]):
    # other statements here

#Executing graphs across compute devices - CPU and GPGPU
list all the devices available for graph
execution:

In [37]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7729484318663983585
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 13340031353424798827
physical_device_desc: "device: XLA_CPU device"
]


When TensorFlow starts executing graphs, it runs the independent paths
within each graph in a separate thread, with each thread running on a separate CPU. We
can restrict the number of threads used for this purpose by changing the number
of `inter_op_parallelism_threads`.

inter_op_parallelism_threads. Similarly, if within an independent path, an
operation is capable of running on multiple threads, TensorFlow will launch that specific
operation on multiple threads. The number of threads in this pool can be changed by setting
the number of `intra_op_parallelism_threads`.

##Placing graph nodes on specific compute devices
Let us enable the logging of variable placement by defining a config object, set the
`log_device_placement` property to `true`, and then pass this `config` object to the session
as follows:

In [40]:
tf.reset_default_graph()

# model parameters
w = tf.Variable([0.3], tf.float32)
b = tf.Variable([-0.3], tf.float32)
# input/output
x = tf.placeholder(tf.float32)
y = w * x + b

# add logging here
config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
  tfs.run(tf.global_variables_initializer())
  print('output', tfs.run(y, {x:[1,2,3,4]}))

output [0.         0.3        0.6        0.90000004]


The variables and operations can be placed on
specific devices by using `tf.device()` function.

In [2]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
  w = tf.get_variable(name='w', initializer=[0.3], dtype=tf.float32)
  b = tf.get_variable(name='b', initializer=[-0.3], dtype=tf.float32)
  x = tf.placeholder(name='x', dtype=tf.float32)
  y = w * x + b
  
config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
  tfs.run(tf.global_variables_initializer())
  print('output', tfs.run(y, {x:[1,2,3,4]}))

output [0.         0.3        0.6        0.90000004]


In [0]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)
with tf.device('/device:GPU:0'):
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

##GPU memory handling
* For multi-GPU systems, set the environment variable 
    
    `CUDA_VISIBLE_DEVICES=<list of device idx>`
    
    `os.environ['CUDA_VISIBLE_DEVICES']='0'`
    
* When you do not want the session to grab all of the memory of the GPU, then
you can use the config option `per_process_gpu_memory_fraction` to allocate
a percentage of memory:

    `config.gpu_options.per_process_gpu_memory_fraction = 0.5`
    
* You can also limit the TensorFlow process to grab only the minimum required
memory at the start of the process.

    `config.gpu_options.allow_growth = True`

#Multiple graphs
The recommended approach is to have multiple subgraphs in a single graph.

In case
you wish to use your own graph instead of the default graph, you can do so with
the `tf.graph()` command.

In [45]:
g = tf.Graph()
output = 0

# linear model
with g.as_default():
  w = tf.Variable([0.3], tf.float32)
  b = tf.Variable([-0.3], tf.float32)
  x = tf.placeholder(tf.float32)
  y = w*x+b
  
with tf.Session(graph=g) as tfs:
  tf.global_variables_initializer().run()
  output = tfs.run(y, {x:[1,2,3,4]})
  
print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


#TensorBoard
Within the context of the running session,
* Initialize global variables
* create `tf.summary.FileWriter` that would  create the output in the `tflogs` folder with the events from the default graph
* fetch the value of node `y`

In [3]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], name='w', dtype=tf.float32)
b = tf.Variable([-.3], name='b', dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    writer = tf.summary.FileWriter('tflogs', tfs.graph)
    print('run(y,{x:3}) : ', tfs.run(y, feed_dict={x: 3}))

run(y,{x:3}) :  [0.6]


Set up TensorBoard in Colab,

In [4]:
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

--2018-11-05 20:36:58--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 52.4.75.11, 52.54.84.112, 54.174.228.92, ...
Connecting to bin.equinox.io (bin.equinox.io)|52.4.75.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5363700 (5.1M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip.2’

ngrok-stable-linux- 100%[===================>]   5.11M  --.-KB/s    in 0.1s    

2018-11-05 20:36:59 (35.1 MB/s) - ‘ngrok-stable-linux-amd64.zip.2’ saved [5363700/5363700]

Archive:  ngrok-stable-linux-amd64.zip
replace ngrok? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [5]:
LOG_DIR = './tflogs'
get_ipython().system_raw(
      'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'.format(LOG_DIR))

get_ipython().system_raw('./ngrok http 6006 &')

! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

http://703196d6.ngrok.io
